#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage:"
  echo "xgfexec prog.xgf prog.py"
  echo "  (prog.xgf is the input xgridfit program;"
  echo "   prog.py is the output python script)"
  return 1
fi

python ../Python/xgridfit.py $1 > $2

